# Generated by Django 6.0.4 on 2026-08-19 15:49

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'area_atuacao',
            },
        ),
        migrations.CreateModel(
            name='Ugai',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('total_vagas', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ugai',
            },
        ),
        migrations.CreateModel(
            name='UnidadesConservacao',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'unidades_conserv',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ori_sexual', models.CharField(choices=[('NA', 'Selecione'), ('M', 'Masculino'), ('F', 'Feminino'), ('NB', 'Não binário'), ('AG', 'Agênero'), ('GF', 'Gênero fluido'), ('OT', 'Outro'), ('PN', 'Prefiro não informar')], max_length=12)),
                ('estado', models.CharField(choices=[('NA', 'Selecione'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=20)),
                ('municipio', models.CharField(max_length=80)),
                ('logradouro', models.CharField(blank=True, max_length=30)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=13)),
                ('rg', models.CharField(max_length=20, unique=True, verbose_name='RG')),
                ('org_emiss', models.CharField(max_length=30, verbose_name='Orgão emissor(RG)')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[core.models.validador_cpf], verbose_name='CPF')),
                ('telefone_fixo', models.CharField(blank=True, max_length=10)),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('profissao', models.CharField(max_length=30, verbose_name='Profissão/Ocupação')),
                ('codigo_recup', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_pessoais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dados_pessoais',
            },
        ),
        migrations.CreateModel(
            name='DadosSolicPesquisa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_public', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.localdate)),
                ('acao_realizada', models.CharField(max_length=80)),
                ('foto', models.CharField(choices=[('NA', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3)),
                ('inicio_atividade', models.DateField(default=django.utils.timezone.localdate)),
                ('final_atividade', models.DateField(default=django.utils.timezone.localdate)),
                ('retorno_comuni', models.CharField(max_length=150)),
                ('gestor_resp', models.CharField(blank=True, max_length=80, null=True)),
                ('recusa_motivo', models.CharField(blank=True, max_length=400, null=True)),
                ('doc_ident', models.FileField(upload_to=core.models.get_path_doc, validators=[core.models.validate_file_size])),
                ('doc_cpf', models.FileField(upload_to=core.models.get_path_doc, validators=[core.models.validate_file_size])),
                ('doc_seg_vida', models.FileField(upload_to=core.models.get_path_doc, validators=[core.models.validate_file_size])),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('PENDENTE', 'Pendente'), ('INDEFERIDO', 'Indeferido'), ('ENCERRADO', 'Encerrado')], max_length=10)),
                ('area_atuacao', models.ManyToManyField(to='core.areaatuacao')),
                ('user_solic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
                ('unidades', models.ManyToManyField(to='core.unidadesconservacao')),
            ],
            options={
                'db_table': 'solic_pesquisa',
            },
        ),
        migrations.CreateModel(
            name='ArquivosRelFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=core.models.get_path_rel)),
                ('upado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('pesquisa_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arq_pesquisa', to='core.dadossolicpesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='AnexExtraPesqOutros',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('doc_url', models.FileField(upload_to=core.models.get_path_doc, validators=[core.models.validate_file_size])),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outros_documentos', to='core.dadossolicpesquisa')),
            ],
            options={
                'db_table': 'anex_pesq_outros',
            },
        ),
        migrations.CreateModel(
            name='AnexExtraPesqLicenca',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('doc_url', models.FileField(upload_to=core.models.get_path_doc, validators=[core.models.validate_file_size])),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='core.dadossolicpesquisa')),
            ],
            options={
                'db_table': 'anex_pesq_licenca',
            },
        ),
        migrations.CreateModel(
            name='DadosSolicUgai',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade_pessoas', models.PositiveIntegerField()),
                ('instituicao', models.CharField(blank=True, max_length=40, null=True, verbose_name='Instituição')),
                ('setor', models.CharField(blank=True, max_length=40, null=True)),
                ('cargo', models.CharField(blank=True, max_length=40, null=True)),
                ('ativ_desenv', models.CharField(max_length=200, verbose_name='Atividades que irá desenvolver')),
                ('publico_alvo', models.CharField(max_length=80, verbose_name='Público alvo')),
                ('recusa_motivo', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('PENDENTE', 'Pendente'), ('INDEFERIDO', 'Indeferido'), ('ENCERRADO', 'Encerrado')], max_length=10)),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.localdate)),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('data_final', models.DateField(default=django.utils.timezone.localdate)),
                ('user_solic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_ugai', to=settings.AUTH_USER_MODEL)),
                ('ugai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='core.ugai')),
            ],
            options={
                'db_table': 'solic_ugai',
            },
        ),
        migrations.CreateModel(
            name='MembroEquipePesq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('ori_sexual', models.CharField(choices=[('mulher_trans', 'Mulher Trans'), ('homem_trans', 'Homem Trans'), ('mulher_cis', 'Mulher Cis'), ('homem_cis', 'Homem Cis'), ('outros', 'Outros')], max_length=12, verbose_name='Orientação sexual')),
                ('instituicao', models.CharField(max_length=80, verbose_name='Instituição')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('email_enviado', models.BooleanField(default=False)),
                ('confirmado', models.BooleanField(default=False)),
                ('token_confirmacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_confirm', models.DateTimeField(blank=True, null=True)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa', to='core.dadossolicpesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoMembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(blank=True, max_length=255, null=True)),
                ('upado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc_ident', models.FileField(upload_to=core.models.get_path_membro_doc, validators=[core.models.validate_file_size])),
                ('doc_cpf', models.FileField(upload_to=core.models.get_path_membro_doc, validators=[core.models.validate_file_size])),
                ('doc_seg_vida', models.FileField(upload_to=core.models.get_path_membro_doc, validators=[core.models.validate_file_size])),
                ('doc_cart_vacin', models.FileField(blank=True, null=True, upload_to=core.models.get_path_membro_doc, validators=[core.models.validate_file_size])),
                ('licenca', models.FileField(blank=True, null=True, upload_to=core.models.get_path_membro_doc, validators=[core.models.validate_file_size])),
                ('outros', models.FileField(blank=True, null=True, upload_to=core.models.get_path_membro_doc, validators=[core.models.validate_file_size])),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.membroequipepesq')),
            ],
        ),
        migrations.CreateModel(
            name='MembroEquipeUGAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(max_length=11)),
                ('cor_raca', models.CharField(choices=[('PRETA', 'Preta'), ('PARDA', 'Parda'), ('INDIGENA', 'Indigena'), ('AMARELA', 'Amarela'), ('BRANCA', 'Branca')], max_length=10)),
                ('genero', models.CharField(choices=[('mulher_trans', 'Mulher Trans'), ('homem_trans', 'Homem Trans'), ('mulher_cis', 'Mulher Cis'), ('homem_cis', 'Homem Cis'), ('outros', 'Outros')], max_length=12)),
                ('data_nasc', models.DateField()),
                ('solicitacao_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='core.dadossolicugai')),
            ],
            options={
                'db_table': 'equipe_ugai',
                'indexes': [models.Index(fields=['solicitacao_ref'], name='equipe_ugai_solicit_9f8f78_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dadossolicugai',
            index=models.Index(fields=['ugai', 'data_inicio', 'data_final'], name='solic_ugai_ugai_id_ab0907_idx'),
        ),
    ]
