# Generated by Django 6.0.4

import uuid
from django.db import migrations, models


def preencher_id_public(apps, schema_editor):
    DadosSolicPesquisa = apps.get_model("core", "DadosSolicPesquisa")
    for solicitacao in DadosSolicPesquisa.objects.filter(id_public__isnull=True):
        solicitacao.id_public = uuid.uuid4()
        solicitacao.save(update_fields=["id_public"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadossolicpesquisa",
            name="id_public",
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
        migrations.RunPython(
            preencher_id_public,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="dadossolicpesquisa",
            name="id_public",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
