# Generated by Django 6.0.4 on 2026-08-20 17:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_id_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadossolicugai',
            name='id_public',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
